### ISSUE TITLE
kat-api is missing/deprecated

### ISSUE THREAD

**Issue by carmona** [PopcornTimeCE/desktop#3]
Seems like https://www.npmjs.com/package/kat-api has been removed from npm registry and can't be installed as a dependency. A new substitute must be found, perhaps this one? https://www.npmjs.com/package/kickass-torrent

ps: I haven't even read the code, just cloned and tried to build it.

**Comment by DiscoveryOV** [comment]
This is definitely an issue we want to fix, getting updated dependencies.

While you obviously don't need to, it would help immensely if you do what you can to find and fix the dependencies listed in **package.json**. Once you've fixed what you can, create a merge request and I'll look it over.

**For now** (since this is a terrible way to fix it) i've added the required dependencies to the git so that anyone can run the app. I'll update the readme shortly.

**Comment by sundaysan** [comment]
Maybe use: https://github.com/isdampe/kat-api

**Comment by paulhobbel** [comment]
Or fork mine this is the original one popcorn time used

**Comment by gungale1** [comment]
Thanks @paulhobbel
